# Generated by Django 4.2.9 on 2024-11-07 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Battery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatteryProcessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_id', models.CharField(max_length=50, unique=True)),
                ('process_type', models.CharField(choices=[('charging', 'Charging'), ('discharging', 'Discharging')], max_length=11)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('battery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Battery.battery')),
            ],
        ),
    ]
