# Generated by Django 4.2.9 on 2024-11-07 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Battery', '0001_initial'),
        ('BatteryProcessLog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatteryCycleData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_number', models.IntegerField()),
                ('voltage', models.FloatField()),
                ('current', models.FloatField()),
                ('temperature', models.FloatField()),
                ('timestamp', models.DateTimeField()),
                ('battery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Battery.battery')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycle_data', to='BatteryProcessLog.batteryprocesslog')),
            ],
        ),
    ]
