# Generated by Django 4.2.9 on 2024-11-07 09:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('nominal_capacity', models.FloatField()),
                ('voltage_min', models.FloatField(default=2.75)),
                ('voltage_max', models.FloatField(default=4.2)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
